name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: mlorpen.informaticamajada.es
          port: 2222
          username: marcoslp
          key: ${{secrets.LARAVELAPP_KEY}}
          script: "cd /var/www/html/MyLaravelApp; ls -al"
